require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Security/Eval:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 135

Rails/DynamicFindBy:
  Exclude:
    - 'app/lib/connectors/opennebula/*.rb'
    - 'spec/connectors/opennebula/*.rb'
    - 'app/models/clouds/opennebula.rb'
    - 'spec/models/clouds/opennebula_spec.rb'
    - 'spec/controllers/v3/auth/tokens_controller_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

RSpec/NestedGroups:
  Enabled: false
