version: 2
jobs:
  build:
    branches:
      ignore:
        - /.*/
    docker:
      - image: docker:stable
    working_directory: /root/keystorm
    steps:
      - run: apk add --no-cache git openssh
      - checkout
      - setup_remote_docker
      - run: |
          TAG=${CIRCLE_TAG#v}
          BRANCH=${TAG/%.*/.x}
          VERSION=${TAG}
          LATEST=$(git tag --sort=-refname | head -n 1)

          docker login -u $DOCKER_USER -p $DOCKER_PASS

          docker build --build-arg branch=$BRANCH --build-arg version="$VERSION" -t therocciproject/keystorm:$TAG .
          docker push therocciproject/keystorm:$TAG

          if [ "$LATEST" == "$CIRCLE_TAG" ]; then
            docker tag therocciproject/keystorm:$TAG therocciproject/keystorm:latest
            docker push therocciproject/keystorm:latest
          fi
deployment:
  fake_deploy_for_cci2:
    tag: /v.*/
    commands:
      - echo "make tags run in 2.0"
