defaults: &defaults
  cloud: opennebula
  opennebula:
    endpoint: http://localhost:2633/RPC2
    secret: oneadmin:opennebula
    api-call-timeout: 3h
  log_level: debug
  token_cipher: AES-128-CBC
  token_key: abcdefghijklmnopqrstuvwxyz
  token_iv: zyxwvutsrqponmlkjihgfedcba
  oidc:
    matcher: urn:mace:egi.eu:aai.egi.eu:{role}@{group}
  voms:
    default_email: nomail@nomail.com

production:
  <<: *defaults
  log_level: info

development:
  <<: *defaults

test:
  <<: *defaults
