
defaults: &defaults
  opennebula:
    endpoint: http://localhost:2633/RPC2
    secret: oneadmin:opennebula
    api-call-timeout: 3h
  log_level: debug
  token_cipher: AES_128_CBC
  token_key: abcdefghijklmnoprstuvxyz
  token_iv: 123456789
  default_email: nomail@nomail.com

production:
  <<: *defaults
  log_level: info

development:
  <<: *defaults

test:
  <<: *defaults
