defaults: &defaults
  cloud: <%= ENV['KEYSTORM_CLOUD'] || 'opennebula' %>
  opennebula:
    endpoint: <%= ENV['KEYSTORM_OPENNEBULA_ENDPOINT'] || 'http://localhost:2633/RPC2' %>
    secret: <%= ENV['KEYSTORM_OPENNEBULA_SECRET'] || 'oneadmin:opennebula' %>
  log_level: <%= ENV['KEYSTORM_LOG_LEVEL'] || 'info' %>
  token_cipher: <%= ENV['KEYSTORM_TOKEN_CIPHER'] || 'AES-128-CBC' %>
  token_key: <%= ENV['KEYSTORM_TOKEN_KEY'] || 'abcdefghijklmnop' %>
  token_iv: <%= ENV['KEYSTORM_TOKEN_IV'] || 'zyxwvutsrqponmlk' %>
  memcache: <%= ENV['KEYSTORM_MEMCACHE'] || 'localhost:11211' %>
  oidc:
    matcher: <%= ENV['KEYSTORM_OIDC_MATCHER'] || 'urn:mace:egi.eu:aai.egi.eu:{role}@{group}' %>
  voms:
    default_email: <%= ENV['KEYSTORM_VOMS_DEFAULT_EMAIL'] || 'nomail@nomail.com' %>
  catalog: # List of catalog entries
    - endpoints:
        - region_id: rOCCILand
          url: http://rocciland.org/v1/service
          region: rOCCILand
          interface: public
          id: 8d243dbd892234d1bccfbfb29f2ad947b2ae4cd2
      type: compute
      id: 82615421269f13b16e8744d2d84509b0c0c76de5
      name: rOCCI

production:
  <<: *defaults
  log_level: info

development:
  <<: *defaults
  log_level: debug

test:
  <<: *defaults
